language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - stable
script:
  - go get -u golang.org/x/lint/golint
  - go test
  - go vet
  - diff -u <(echo -n) <(golint ./...)
after_success:
  - ./scripts/coverage.sh